Models/State.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eDominerUser.Models
{
    public class State
    {
        public int StateId { get; set; }
        [Required]
        public string StateName { get; set; }
    }
}

Models/eDominerUserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace eDominerUser.Models
{
    public class eDominerUserModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Plese Enter the Name")]
        [RegularExpression(@"^(([A-za-z]+[\s]{1}[A-za-z]+)|([A-Za-z]+))$")]
        public string Name { get; set; }


        [Required]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a valid e-mail adress")]
        [DataType(DataType.EmailAddress)]
        public string EmailId { get; set; }

        [Required(ErrorMessage = "You must provide a phone number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string MobileNumber { get; set; }
        [Required]
        public string Address { get; set; }

        [Required]
        public string Gender { get; set; }
        [Required]
        public string StateName { get; set; }
        [Required]
        public string Hobbies { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eDominerUser.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/eDominerUsersController.cs
using eDominerUser.Models;
using eDominerUser.Repository;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;

namespace eDominerUser.Controllers
{
    public class eDominerUsersController : Controller
    {
        eDominerUserRepo dominerUserRepo = new eDominerUserRepo();
        // GET: eDominerUsers
        [HttpGet]
        public ActionResult UserAdd()
        {

            return View();
        }

        [HttpPost]
        public ActionResult UserAdd(eDominerUserModel eDominer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    eDominerUserRepo eDominerUser = new eDominerUserRepo();

                    if (eDominerUser.AddUser(eDominer))
                    {
                        ViewBag.Message = "User Added successfully";
                        ModelState.Clear();
                    }
                    return View();
                }
                return RedirectToAction(nameof(GetAllEmpDetails));
            }
            catch
            {
                return View();
            }

            //return View();
        }



        [HttpGet]
        public ActionResult GetAllEmpDetails()
        {
            ModelState.Clear();
            var list = dominerUserRepo.GetAllRecod();
            if (list.Count == 0)
            {
                TempData["alertMessage"] = "Currently Data Table has  not Avaiable Data";
            }
            //else
            //{
            //    if (string.IsNullOrEmpty(Searchvalue))
            //    {
            //        ViewBag["ms"] = "This User is Not Avilable In the DataBase!";
            //        return View(list);
            //    }
            //    //else
            //    //{
            //    //    if (Searchvalue.ToLower() == "Searchvalue")

            //    //    {
            //    //        var search = list.Where(p => p.Name.ToLower().Contains(Searchvalue.ToLower()));
            //    //        return View(search);
            //    //    }
            //    //}
            //}
            return View(list);
        }


        [HttpGet]
        public ActionResult EditEmpDetails(int Id)
        {
            eDominerUserRepo eDominerUser = new eDominerUserRepo();

            var uselist = eDominerUser.GetUserById(Id).FirstOrDefault();
            if (uselist == null)
            {
                return RedirectToAction("GetAllEmpDetails");
            }
            return View(uselist);

        }


        [HttpPost, ActionName("EditEmpDetails")]
        public ActionResult EditEmpDetails(eDominerUserModel dominerUserModel)
        {
            try
            {
                eDominerUserRepo eDominerUser = new eDominerUserRepo();
                eDominerUser.UpdateUser(dominerUserModel);

                return RedirectToAction("GetAllEmpDetails");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Deleted(int Id)
        {
            try
            {
                eDominerUserRepo eDominerUserRepo = new eDominerUserRepo();
                if (eDominerUserRepo.DeleteEmployee(Id))
                {
                    ViewBag.AlertMsg = "Employee details deleted successfully";

                }
                return RedirectToAction("GetAllEmpDetails");

            }
            catch
            {
                return View();
            }
        }



        [HttpGet]
        public ActionResult StateList(int StateId)
        {
            eDominerUserRepo eDominerUser = new eDominerUserRepo();
            var uselist = eDominerUser.GetState(StateId).FirstOrDefault();
            if (uselist == null)
            {
                return RedirectToAction("GetAllEmpDetails");
            }
            return View(uselist);

        }


    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("eDominer User Added Here!", "UserAdd", "eDominerUsers", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/eDominerUsers/Deleted.cshtml
@model eDominerUser.Models.eDominerUserModel

@{
    ViewBag.Title = "Deleted";
}



<h3 style="background-color:aquamarine;color:coral">Are you sure you want to delete this?</h3>
<div>
    <h2> User Deleted</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MobileNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MobileNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hobbies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hobbies)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "UserAdd")
        </div>
    }
</div>

Views/eDominerUsers/EditEmpDetails.cshtml
@model eDominerUser.Models.eDominerUserModel

@{
    ViewBag.Title = "EditEmpDetails";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/css/multi-select-tag.css">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4 style="color:crimson;background-color:bisque">eDominer User Update</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                Male:   @Html.RadioButton("Gender", "Male")
                Female: @Html.RadioButton("Gender", "Female")
                TransGender:   @Html.RadioButton("Gender", "TransGender")
                Other: @Html.RadioButton("Gender", "Other")

            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.StateName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select class="form-control" id="StateName" name="StateName" required>
                            <option>Select StateName</option>
                            <option value="Bihar" name="Bihar" selected>Bihar</option>
                            <option value="WestBengal" name="WestBengal">WestBengal</option>
                            <option value="M.P" name="M.P">M.P</option>
                            <option value="U.P" name="U.P">U.P</option>
                            <option value="Jharkhand" name="Jharkhand">Jharkhand</option>
                            <option value="Gujarat" name="Gujarat">Gujarat</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Hobbies, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select class="form-control" id="Hobbies" name="Hobbies" multiple>
                           
                            <option value="Criecket" name="Criecket" selected>Criecket</option>
                            <option value="Luddu" name="Luddu">Luddu</option>
                            <option value="Chess" name="Chess">Chess</option>
                            <option value="Tableteniess" name="Tableteniess">Tableteniess</option>
                            <option value="IndoorGame" name="IndoorGame">IndoorGame</option>
                            <option value="Outerdoor" name="Outerdoor">Outerdoor</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List GetAllEmpDetails", "GetAllEmpDetails")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>

<script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/js/multi-select-tag.js"></script>

<script type="text/javascript">
    new MultiSelectTag('Hobbies')
</script>

Views/eDominerUsers/GetAllEmpDetails.cshtml
@model IEnumerable<eDominerUser.Models.eDominerUserModel>

@{
    ViewBag.Title = "GetAllEmpDetails";
}

<h2>Get All EmpDetails</h2>
@if (TempData["alertMessage"]!=null)
{
<div class="alert alert-info">
   <strong>*Message*</strong> @TempData["alertMessage"]
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span>x</span>
    </button>
</div>
}


<p>
    @Html.ActionLink("Add New User Recod", "UserAdd",null, new {@class="btn btn-primary"})
</p>
@*<div>
    @using (Html.BeginForm("State", "eDominerUser", FormMethod.Get))
    {
        <select class="form-control" id="State" name="State" required>
            <option>Select StateName</option>
            <input type="text" name="State" id="State"/>
        </select>
        <br />
    }
</div>*@
<table class="table table-bordered  table-hover table-responsive">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MobileNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StateName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hobbies)
        </th>
        <th>
            Action
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MobileNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StateName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hobbies)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditEmpDetails", new { id = item.Id }, new { @class = "btn btn-primary" })|  @*&&*@
            @Html.ActionLink("Delete", "Deleted", new { id = item.Id }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>

Views/eDominerUsers/UserAdd.cshtml
@model eDominerUser.Models.eDominerUserModel

@{
    ViewBag.Title = "UserAdd";
}


<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/css/multi-select-tag.css">

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h2>User Add Here </h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    Male:   @Html.RadioButton("Gender", "Male")
                    Female: @Html.RadioButton("Gender", "Female")
                    TransGender:   @Html.RadioButton("Gender", "TransGender")
                    Other: @Html.RadioButton("Gender", "Other")

                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.StateName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select class="form-control" id="StateName" name="StateName">
                        <option>Select StateName</option>
                        <option value="Bihar" name="Bihar">Bihar</option>
                        <option value="WestBengal" name="WestBengal">WestBengal</option>
                        <option value="M.P" name="M.P">M.P</option>
                        <option value="U.P" name="U.P">U.P</option>
                        <option value="Jharkhand" name="Jharkhand">Jharkhand</option>
                        <option value="Gujarat" name="Gujarat">Gujarat</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
 
        <div class="col-md-8">
            <div class="form-group">
                @Html.LabelFor(model => model.Hobbies, htmlAttributes: new { @class = "control-label col-md-2" })
              <div class="col-md-10">
              <select class="form-control" id="Hobbies" name="Hobbies" multiple>
                <option value="Criecket" name="Criecket">Criecket</option>
                <option value="Luddu" name="Luddu">Luddu</option>
                <option value="Chess" name="Chess">Chess</option>
                <option value="Tableteniess" name="Tableteniess">Tableteniess</option>
                <option value="IndoorGame" name="IndoorGame">IndoorGame</option>
                <option value="Outerdoor" name="Outerdoor">Outerdoor</option>
            </select>
            </div>
            </div>
        </div>
       
    <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="color:green">
                @ViewBag.Message

            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "GetAllEmpDetails")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>

<script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag/dist/js/multi-select-tag.js"></script>

<script type="text/javascript">
    new MultiSelectTag('Hobbies')  
</script>